frontend:
  urls:
    - "http://localhost:3000"
    - "http://localhost:3001"
    - "https://canteen-web-mu.vercel.app"
    - "https://canteen-admin-orcin.vercel.app"

backend:
  apis:
    user_portal: "https://canteenweb-production.up.railway.app/"
    admin_portal: "https://canteenadmin-production-cdae.up.railway.app/"
