frontend:
  urls:
    - "http://localhost:3000"
    - "http://localhost:3001"
    - "https://canteenz.vercel.app"
    - "https://admin-canteenz.vercel.app"

backend:
  apis:
    user_portal: "http://localhost:3002"
    admin_portal: "http://localhost:5000"
